format_version: 2
pipelines:
  pipeline-name: sand-test
    group: group-name
    materials:
      git-repo:
        git: https://github.com/sanmcdaniel/vue-gotham-todo.git
        branch: master
    stages:
      - first-stage:
          jobs:
            list:
              tasks:
                - exec:
                    command: ls -al
                    arguments:
                      - .
